### PR TITLE
Make 'legg til i ditt dashboard' button scale with different viewport sizes

### LINKED ISSUE #127: "Legg til i ditt dashboard"  button doesn't fit on smaller screen sizes
The text of this button does not fit on my screen. Maybe remove some text or make the button higher?

_Originally posted by @emilom in https://github.com/IT2901-SINTEF01/frontend/pull/124#discussion_r613383840_

### PR DESCRIPTION
**Pull request by emilom**
The button now looks good on all viewport sizes.

Close #127

### CODE REVIEW

**Review by FredrikAugust — CHANGES_REQUESTED** [review]
The new design:
Screenshot 2021-04-21 at 10 47 42

The old design:
Screenshot 2021-04-21 at 10 48 07

-------

The new design is no longer in thread with the Evergreen UI component design, and thus not in alignment with the design from @thomran.

I believe it would be beneficial if we kept a uniform set of UI components.

Other approaches to this;
- `line-height: 1em` on the button/text
- Make the control size bigger
- Confer Thomas about moving the button

**Comment by emilom** [comment]
The new design:
Screenshot 2021-04-21 at 10 47 42

The updated new design:
Screenshot 2021-04-21 at 12 20 16

The old design:
Screenshot 2021-04-21 at 10 48 07

-------


The font size is still off and differs from other buttons in the library.

Could you perhaps just shorten the text in the button, or set the line height to e.g. `1.2em` instead? Do we need the entire "Legg til i **ditt** dashboard"? Could we omit "ditt"?

This is of course just nit-pick, but differing from the component library is something best avoided unless absolutely needed.

This would also serve as something worth mentioning in the report; Evergreen isn't a very mature library and is missing some features we would benefit from.

**Comment by FredrikAugust** [comment]
And if not, could you perhaps try inherting font size (and eventual other differing attributes) from the button? 

https://developer.mozilla.org/en-US/docs/Web/CSS/inherit

**Review by FredrikAugust — CHANGES_REQUESTED** [review]
See comments above.

**Comment by FredrikAugust** [comment]
LGTM as soon as the tests are updated!

**Review by FredrikAugust — DISMISSED** [review]

**Review by FredrikAugust — APPROVED** [review]
GJ!

**Pull request merged**
